services:
  core-api:
    build:
      context: .
      dockerfile: packages/core-api/Dockerfile
    network_mode: "host"
    env_file:
      - .env
    environment:
      - DATABASE_URL=file:./core.db
    restart: always

  bot-service:
    build:
      context: .
      dockerfile: packages/bot-service/Dockerfile
    depends_on:
      - core-api
    network_mode: "host"
    env_file:
      - .env
    environment:
      - DATABASE_URL=file:./bot.db
    restart: always
